language: elixir
elixir:
  - 1.1.1
  - 1.2.1
otp_release:
  - 18.0
  - 18.1
sudo: required
before_install:
  - source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install rethinkdb -y --force-yes
before_script: rethinkdb --daemon
install:
  - mix local.hex --force
  - mix deps.get --only test
